"use strict";var c=Object.defineProperty;var d=Object.getOwnPropertyDescriptor;var g=Object.getOwnPropertyNames;var S=Object.prototype.hasOwnProperty;var x=(i,e)=>{for(var t in e)c(i,t,{get:e[t],enumerable:!0})},f=(i,e,t,n)=>{if(e&&typeof e=="object"||typeof e=="function")for(let a of g(e))!S.call(i,a)&&a!==t&&c(i,a,{get:()=>e[a],enumerable:!(n=d(e,a))||n.enumerable});return i};var v=i=>f(c({},"__esModule",{value:!0}),i);var E={};x(E,{default:()=>m});module.exports=v(E);var s=require("obsidian"),b={},m=class extends s.Plugin{async onload(){await this.loadSettings(),this.addCommand({id:"open-summary-modal",name:"Open summary editor",callback:()=>{this.openSummaryModal()}}),this.addSettingTab(new y(this.app,this))}onunload(){}async loadSettings(){this.settings=Object.assign({},b,await this.loadData())}async saveSettings(){await this.saveData(this.settings)}openSummaryModal(){let e=this.app.workspace.getActiveFile();e&&new l(this.app,this,e).open()}},l=class extends s.Modal{constructor(t,n,a){super(t);this.existingSummary="";this.plugin=n,this.file=a}async onOpen(){let{contentEl:t}=this;t.empty(),t.addClass("my-summary-modal"),t.createEl("h2",{text:"My Summary"}),await this.loadExistingSummary();let n=t.createDiv();this.textArea=new s.TextAreaComponent(n),this.textArea.inputEl.addClass("my-summary-textarea"),this.textArea.inputEl.placeholder="Enter your summary here...",this.textArea.setValue(this.existingSummary);let a=t.createDiv("my-summary-button-container");a.createEl("button",{text:"Cancel",cls:"my-summary-button my-summary-cancel-button"}).addEventListener("click",()=>{this.close()}),a.createEl("button",{text:"Save",cls:"my-summary-button my-summary-save-button"}).addEventListener("click",async()=>{await this.saveSummary(),this.close()}),this.textArea.inputEl.focus()}onClose(){let{contentEl:t}=this;t.empty()}async loadExistingSummary(){try{let t=await this.app.vault.read(this.file),n=t;if(t.startsWith(`---
`)){let r=t.indexOf(`
---
`,4);r!==-1&&(n=t.substring(r+5))}let a=n.match(/^## 0\. My Summary\n([\s\S]*?)(?=\n## |$)/m);a&&a[1]&&(this.existingSummary=a[1].trim())}catch(t){console.error("Error loading existing summary:",t)}}async saveSummary(){try{let t=this.textArea.getValue().trim();if(!t)return;let n=await this.app.vault.read(this.file),a="",r=n;if(n.startsWith(`---
`)){let u=n.indexOf(`
---
`,4);u!==-1&&(a=n.substring(0,u+5),r=n.substring(u+5))}let h=/^## 0\. My Summary\n[\s\S]*?(?=\n## |$)/m;r=r.replace(h,"").trim();let p=`## 0. My Summary

${t}
`,o=a;a&&!a.endsWith(`
`)&&(o+=`
`),o+=p,r&&(o+=`
`+r),await this.app.vault.modify(this.file,o)}catch(t){console.error("Error saving summary:",t)}}},y=class extends s.PluginSettingTab{constructor(e,t){super(e,t),this.plugin=t}display(){let{containerEl:e}=this;e.empty(),e.createEl("h2",{text:"My Summary Settings"}),new s.Setting(e).setName("Keyboard shortcut").setDesc('Configure the keyboard shortcut in Settings \u2192 Hotkeys \u2192 Search for "My Summary"').addButton(t=>t.setButtonText("Open Hotkeys Settings").onClick(()=>{this.app.setting.openTabById("hotkeys"),this.app.setting.activeTab.searchInputEl.value="My Summary",this.app.setting.activeTab.updateHotkeyVisibility()})),new s.Setting(e).setName("About").setDesc("This plugin helps you create and manage personal summaries based on Kim Ik-han's archiving methodology.")}};
